(find-file "..")
(end-of-buffer)
(split-window)
(beginning-of-buffer)
(find-file "foo.txt")
(erase)
(delete-window)
(select-buffer "foo.txt")
(insert "line1\n")
(insert "line2 is little longer than line1\n")
(insert "  1234567890")
(backward-char 10)
(delete 10)
(delete 3)
(insert "\n\n\n\n\n\n\n\n")
(insert "foo")
(insert "  bar  \nbaz")
(insert "\nwhat line is this line?\n")
(beginning-of-buffer)
(search-forward "li")
(search-forward "li")
(search-forward "li")
(search-forward "li")
(search-forward "li")
(beginning-of-buffer)
(search-forward "lin")
(search-forward "lin")
(search-forward "lin")
(search-backward "li")
(search-backward "li")
(search-backward "li")
(search-backward "li")
(search-backward "li")
(beginning-of-buffer)
(search-forward "le")
(beginning-of-line)
(search-forward "lo")
(end-of-buffer)
(search-backward "le")
(end-of-buffer)
(search-backward "lo")
(end-of-buffer)
(search-backward "line")
(previous-line)
(next-line)
(goto-line 4)
(forward-char)
(forward-char 10)
(backward-char)
(backward-char 100)
(insert "hoge")
(beginning-of-line)
(delete 7)
(beginning-of-line)
(end-of-line)
(save-buffer)

(list-buffers)
(select-buffer "*Buffer List*")
(print-buffers)
